-- 0081_enforcement_stage_rpc.sql
-- Adds a secure RPC to update enforcement stages with audit logging.

-- migrate:up

CREATE TABLE IF NOT EXISTS public.enforcement_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    judgment_id bigint NOT NULL,
    stage text NOT NULL,
    note text,
    changed_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
    changed_by text
);

COMMENT ON TABLE public.enforcement_history IS 'Audit log of enforcement stage changes.';
COMMENT ON COLUMN public.enforcement_history.judgment_id IS 'References public.judgments.id';

CREATE INDEX IF NOT EXISTS enforcement_history_judgment_id_idx
ON public.enforcement_history (judgment_id);

CREATE OR REPLACE FUNCTION public.set_enforcement_stage(
    _judgment_id bigint,
    _new_stage text,
    _note text DEFAULT NULL,
    _changed_by text DEFAULT NULL
)
RETURNS public.judgments
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    allowed_stages constant text[] := ARRAY[
        'levy_issued',
        'payment_plan',
        'waiting_payment',
        'pre_enforcement',
        'paperwork_filed',
        'collected',
        'closed_no_recovery'
    ];
    normalized_stage text;
    current_row public.judgments%ROWTYPE;
BEGIN
    IF _judgment_id IS NULL THEN
        RAISE EXCEPTION 'judgment id is required';
    END IF;

    IF _new_stage IS NULL THEN
        RAISE EXCEPTION 'new stage is required';
    END IF;

    normalized_stage := trim(lower(_new_stage));

    IF normalized_stage = '' THEN
        RAISE EXCEPTION 'new stage is required';
    END IF;

    IF NOT normalized_stage = ANY(allowed_stages) THEN
        RAISE EXCEPTION 'invalid enforcement stage: %', _new_stage;
    END IF;

    SELECT *
    INTO current_row
    FROM public.judgments
    WHERE id = _judgment_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'judgment % not found', _judgment_id;
    END IF;

    IF coalesce(current_row.enforcement_stage, '') = normalized_stage THEN
        RETURN current_row;
    END IF;

    UPDATE public.judgments
    SET enforcement_stage = normalized_stage,
        enforcement_stage_updated_at = timezone('utc', now())
    WHERE id = _judgment_id
    RETURNING *
    INTO current_row;

    INSERT INTO public.enforcement_history (judgment_id, stage, note, changed_at, changed_by)
    VALUES (
        _judgment_id,
        normalized_stage,
        nullif(trim(_note), ''),
        timezone('utc', now()),
        nullif(trim(_changed_by), '')
    );

    RETURN current_row;
END;
$$;

REVOKE ALL ON FUNCTION public.set_enforcement_stage(
    bigint, text, text, text
) FROM public;
GRANT EXECUTE ON FUNCTION public.set_enforcement_stage(
    bigint, text, text, text
) TO anon,
authenticated;
GRANT EXECUTE ON FUNCTION public.set_enforcement_stage(
    bigint, text, text, text
) TO service_role;

-- migrate:down

REVOKE EXECUTE ON FUNCTION public.set_enforcement_stage(
    bigint, text, text, text
) FROM anon,
authenticated,
service_role;
DROP FUNCTION IF EXISTS public.set_enforcement_stage (bigint, text, text, text);

DROP INDEX IF EXISTS enforcement_history_judgment_id_idx;
DROP TABLE IF EXISTS public.enforcement_history;

-- Purpose: Provide a centralized RPC for updating enforcement stages while logging history.
