-- 0081_enforcement_stage_rpc.sql
-- Adds a secure RPC to update enforcement stages with audit logging.

-- migrate:up

create table if not exists public.enforcement_history (
    id bigint generated by default as identity primary key,
    judgment_id bigint not null,
    stage text not null,
    note text,
    changed_at timestamptz not null default timezone('utc', now()),
    changed_by text
);

comment on table public.enforcement_history is 'Audit log of enforcement stage changes.';
comment on column public.enforcement_history.judgment_id is 'References public.judgments.id';

create index if not exists enforcement_history_judgment_id_idx
on public.enforcement_history (judgment_id);

create or replace function public.set_enforcement_stage(
    _judgment_id bigint,
    _new_stage text,
    _note text default NULL,
    _changed_by text default NULL
)
returns public.judgments
language plpgsql
security definer
as $$
DECLARE
    allowed_stages constant text[] := ARRAY[
        'levy_issued',
        'payment_plan',
        'waiting_payment',
        'pre_enforcement',
        'paperwork_filed',
        'collected',
        'closed_no_recovery'
    ];
    normalized_stage text;
    current_row public.judgments%ROWTYPE;
BEGIN
    IF _judgment_id IS NULL THEN
        RAISE EXCEPTION 'judgment id is required';
    END IF;

    IF _new_stage IS NULL THEN
        RAISE EXCEPTION 'new stage is required';
    END IF;

    normalized_stage := trim(lower(_new_stage));

    IF normalized_stage = '' THEN
        RAISE EXCEPTION 'new stage is required';
    END IF;

    IF NOT normalized_stage = ANY(allowed_stages) THEN
        RAISE EXCEPTION 'invalid enforcement stage: %', _new_stage;
    END IF;

    SELECT *
    INTO current_row
    FROM public.judgments
    WHERE id = _judgment_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'judgment % not found', _judgment_id;
    END IF;

    IF coalesce(current_row.enforcement_stage, '') = normalized_stage THEN
        RETURN current_row;
    END IF;

    UPDATE public.judgments
    SET enforcement_stage = normalized_stage,
        enforcement_stage_updated_at = timezone('utc', now())
    WHERE id = _judgment_id
    RETURNING *
    INTO current_row;

    INSERT INTO public.enforcement_history (judgment_id, stage, note, changed_at, changed_by)
    VALUES (
        _judgment_id,
        normalized_stage,
        nullif(trim(_note), ''),
        timezone('utc', now()),
        nullif(trim(_changed_by), '')
    );

    RETURN current_row;
END;
$$;

revoke all on function public.set_enforcement_stage(
    bigint, text, text, text
) from public;
grant execute on function public.set_enforcement_stage(
    bigint, text, text, text
) to anon,
authenticated;
grant execute on function public.set_enforcement_stage(
    bigint, text, text, text
) to service_role;

-- migrate:down

revoke execute on function public.set_enforcement_stage(
    bigint, text, text, text
) from anon,
authenticated,
service_role;
drop function if exists public.set_enforcement_stage(bigint, text, text, text);

drop index if exists enforcement_history_judgment_id_idx;
drop table if exists public.enforcement_history;

-- Purpose: Provide a centralized RPC for updating enforcement stages while logging history.
