-- 0082_judgment_priority_rpc.sql
-- Introduce manual priority metadata for judgments along with a canonical RPC.
-- migrate:up
ALTER TABLE public.judgments
ADD COLUMN IF NOT EXISTS priority_level text,
ADD COLUMN IF NOT EXISTS priority_level_updated_at timestamptz;
UPDATE public.judgments
SET priority_level = COALESCE(NULLIF(priority_level, ''), 'normal')
WHERE
    priority_level IS NULL
    OR BTRIM(priority_level) = '';
UPDATE public.judgments
SET
    priority_level_updated_at = COALESCE(
        priority_level_updated_at,
        TIMEZONE('utc', NOW())
    )
WHERE priority_level_updated_at IS NULL;
ALTER TABLE public.judgments
ALTER COLUMN priority_level
SET DEFAULT 'normal',
ALTER COLUMN priority_level
SET NOT NULL,
ALTER COLUMN priority_level_updated_at
SET DEFAULT TIMEZONE('utc', NOW()),
ALTER COLUMN priority_level_updated_at
SET NOT NULL;
DO $$
DECLARE existing_constraint text;
BEGIN
SELECT conname INTO existing_constraint
FROM pg_constraint
WHERE conrelid = 'public.judgments'::regclass
    AND contype = 'c'
    AND conname = 'judgments_priority_level_allowed';
IF existing_constraint IS NOT NULL THEN EXECUTE format(
    'ALTER TABLE public.judgments DROP CONSTRAINT %I',
    existing_constraint
);
END IF;
END $$;
ALTER TABLE public.judgments
ADD CONSTRAINT judgments_priority_level_allowed CHECK (
    priority_level IN ('low', 'normal', 'high', 'urgent', 'on_hold')
);
CREATE TABLE IF NOT EXISTS public.judgment_priority_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    judgment_id bigint NOT NULL REFERENCES public.judgments (
        id
    ) ON DELETE CASCADE,
    priority_level text NOT NULL,
    note text,
    changed_at timestamptz NOT NULL DEFAULT TIMEZONE('utc', NOW()),
    changed_by text
);
CREATE INDEX IF NOT EXISTS judgment_priority_history_judgment_id_idx ON public.judgment_priority_history (
    judgment_id, changed_at DESC
);
CREATE OR REPLACE FUNCTION public.set_judgment_priority(
    _judgment_id bigint,
    _priority_level text,
    _note text DEFAULT NULL,
    _changed_by text DEFAULT NULL
) RETURNS public.judgments LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE allowed_levels constant text [] := ARRAY ['low', 'normal', 'high', 'urgent', 'on_hold'];
normalized_level text;
trimmed_note text;
trimmed_changed_by text;
current_row public.judgments %ROWTYPE;
BEGIN IF _judgment_id IS NULL THEN RAISE EXCEPTION 'judgment id is required' USING ERRCODE = '22023';
END IF;
normalized_level := trim(lower(COALESCE(_priority_level, '')));
IF normalized_level = ''
OR normalized_level NOT IN (
    SELECT UNNEST(allowed_levels)
) THEN RAISE EXCEPTION 'invalid judgment priority: %',
_priority_level USING ERRCODE = '22023';
END IF;
trimmed_note := NULLIF(trim(COALESCE(_note, '')), '');
trimmed_changed_by := NULLIF(trim(COALESCE(_changed_by, '')), '');
SELECT * INTO current_row
FROM public.judgments
WHERE id = _judgment_id FOR
UPDATE;
IF NOT FOUND THEN RAISE EXCEPTION 'judgment % not found',
_judgment_id USING ERRCODE = 'P0002';
END IF;
IF COALESCE(current_row.priority_level, 'normal') = normalized_level THEN RETURN current_row;
END IF;
UPDATE public.judgments
SET priority_level = normalized_level,
    priority_level_updated_at = timezone('utc', now())
WHERE id = _judgment_id
RETURNING * INTO current_row;
INSERT INTO public.judgment_priority_history (
        judgment_id,
        priority_level,
        note,
        changed_at,
        changed_by
    )
VALUES (
        _judgment_id,
        normalized_level,
        trimmed_note,
        timezone('utc', now()),
        trimmed_changed_by
    );
RETURN current_row;
END;
$$;
REVOKE ALL ON FUNCTION public.set_judgment_priority(bigint, text, text, text)
FROM public;
GRANT EXECUTE ON FUNCTION public.set_judgment_priority(
    bigint, text, text, text
) TO anon,
authenticated,
service_role;
-- migrate:down
REVOKE EXECUTE ON FUNCTION public.set_judgment_priority(
    bigint, text, text, text
)
FROM anon,
authenticated,
service_role;
DROP FUNCTION IF EXISTS public.set_judgment_priority (bigint, text, text, text);
DROP INDEX IF EXISTS judgment_priority_history_judgment_id_idx;
DROP TABLE IF EXISTS public.judgment_priority_history;
DO $$ BEGIN IF EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'public.judgments'::regclass
        AND contype = 'c'
        AND conname = 'judgments_priority_level_allowed'
) THEN
ALTER TABLE public.judgments DROP CONSTRAINT judgments_priority_level_allowed;
END IF;
END $$;
ALTER TABLE public.judgments DROP COLUMN IF EXISTS priority_level_updated_at,
DROP COLUMN IF EXISTS priority_level;
