create or replace function public.insert_case(payload jsonb)
returns jsonb
language plpgsql
security definer
as $$
declare
  cols text[] := '{}';
  vals text[] := '{}';
  has_cases bool;
  use_id boolean := false;
  new_id uuid;
begin
  select exists (
    select 1 from information_schema.tables
    where table_schema='judgments' and table_name='cases'
  ) into has_cases;
  if not has_cases then
    raise exception 'judgments.cases not found';
  end if;

  -- identifier is generated by table default; we only return it.
  -- Map common input keys
  if payload ? 'index_no' then
    cols := cols || 'index_no';
    vals := vals || quote_nullable(payload->>'index_no');
  elsif payload ? 'index_number' then
    cols := cols || 'index_no';
    vals := vals || quote_nullable(payload->>'index_number');
  end if;

  if payload ? 'court' then
    cols := cols || 'court';
    vals := vals || quote_nullable(payload->>'court');
  end if;

  if payload ? 'county' then
    cols := cols || 'county';
    vals := vals || quote_nullable(payload->>'county');
  end if;

  if payload ? 'status' then
    cols := cols || 'status';
    vals := vals || quote_nullable(payload->>'status');
  else
    cols := cols || 'status';
    vals := vals || quote_nullable('new');
  end if;

  if payload ? 'source' then
    cols := cols || 'source';
    vals := vals || quote_nullable(payload->>'source');
  end if;

  if payload ? 'principal_amt' then
    cols := cols || 'principal_amt';
    vals := vals || (payload->>'principal_amt');
  end if;

  if payload ? 'judgment_at' then
    cols := cols || 'judgment_at';
    vals := vals || quote_nullable(payload->>'judgment_at');
  end if;

  execute format(
    'insert into judgments.cases(%s) values(%s) returning coalesce(case_id, id)::uuid',
    array_to_string(cols, ','),
    array_to_string(vals, ',')
  )
  into new_id;

  return jsonb_build_object('ok', true, 'case_id', new_id);
end $$;

grant execute on function public.insert_case(jsonb) to anon, authenticated, service_role;
