-- Creates the main table for storing all judgments
CREATE TABLE judgments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),

    -- Data from the court file
    case_number TEXT,
    plaintiff_name TEXT,
    defendant_name TEXT,
    judgment_amount NUMERIC(10, 2), -- Stores numbers like 12345.67
    entry_date DATE,

    -- This is a 'best practice' field to track your uploads
    -- Stores the name of the file (e.g., "judgments_oct_2025.csv")
    source_file TEXT,

    -- Unique constraint to prevent uploading the same case twice
    -- This assumes 'case_number' should be unique.
    -- If not, you can remove this constraint.
    CONSTRAINT unique_case_number UNIQUE (case_number)
);

-- Optional: Create an index for faster searching by defendant
CREATE INDEX idx_defendant_name ON judgments (defendant_name);

-- Tell Supabase to recognize the new table
NOTIFY pgrst, 'reload schema';

