-- ============================================================================
-- Gig Economy Garnishment Module
-- ============================================================================
-- Creates infrastructure for detecting gig platform employment and generating
-- targeted garnishment subpoenas to registered agents.
-- ============================================================================
-- Ensure intelligence schema exists
CREATE SCHEMA IF NOT EXISTS intelligence;
-- Grant usage if needed
GRANT USAGE ON SCHEMA intelligence TO authenticated,
    anon,
    service_role;
-- ============================================================================
-- GIG PLATFORMS TABLE
-- ============================================================================
-- Stores registered agent addresses for major gig economy platforms.
-- Used by gig_service.py to generate subpoenas addressed to legal departments.
CREATE TABLE IF NOT EXISTS intelligence.gig_platforms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_name TEXT NOT NULL UNIQUE,
    -- Registered agent / legal department address
    registered_agent_name TEXT,
    registered_agent_address TEXT NOT NULL,
    registered_agent_city TEXT,
    registered_agent_state TEXT,
    registered_agent_zip TEXT,
    -- Detection keywords (comma-separated patterns to match in enrichment data)
    detection_keywords TEXT [] DEFAULT '{}',
    -- Subpoena instructions / notes
    subpoena_notes TEXT,
    -- Metadata
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
-- Index for lookups
CREATE INDEX IF NOT EXISTS idx_gig_platforms_name ON intelligence.gig_platforms(platform_name);
CREATE INDEX IF NOT EXISTS idx_gig_platforms_active ON intelligence.gig_platforms(is_active)
WHERE is_active = TRUE;
-- ============================================================================
-- SEED DATA - Major Gig Platforms
-- ============================================================================
INSERT INTO intelligence.gig_platforms (
        platform_name,
        registered_agent_name,
        registered_agent_address,
        registered_agent_city,
        registered_agent_state,
        registered_agent_zip,
        detection_keywords,
        subpoena_notes
    )
VALUES (
        'Uber',
        'CT Corporation System',
        '1515 3rd Street',
        'San Francisco',
        'CA',
        '94158',
        ARRAY ['uber', 'uber technologies', 'uber eats', 'uber driver'],
        'Subpoena to Uber Technologies, Inc. Legal Department. Include driver/account holder SSN or email if known.'
    ),
    (
        'DoorDash',
        'DoorDash Legal Department',
        '303 2nd Street, Suite 800',
        'San Francisco',
        'CA',
        '94107',
        ARRAY ['doordash', 'door dash', 'dasher'],
        'Subpoena to DoorDash, Inc. Dashers are classified as contractors; request 1099 records.'
    ),
    (
        'Lyft',
        'CT Corporation System',
        '185 Berry Street, Suite 5000',
        'San Francisco',
        'CA',
        '94107',
        ARRAY ['lyft', 'lyft driver', 'lyft inc'],
        'Subpoena to Lyft, Inc. Legal Department. Include driver SSN or email if known.'
    ),
    (
        'Instacart',
        'The Corporation Trust Company',
        '50 Beale Street, Suite 600',
        'San Francisco',
        'CA',
        '94105',
        ARRAY ['instacart', 'insta cart', 'instacart shopper'],
        'Subpoena to Maplebear Inc. d/b/a Instacart. Request shopper payment records.'
    ),
    (
        'Grubhub',
        'CT Corporation System',
        '111 W. Washington Street, Suite 2100',
        'Chicago',
        'IL',
        '60602',
        ARRAY ['grubhub', 'grub hub', 'seamless'],
        'Subpoena to Grubhub Holdings Inc. May also be branded as Seamless.'
    ),
    (
        'Amazon Flex',
        'Corporation Service Company',
        '410 Terry Avenue North',
        'Seattle',
        'WA',
        '98109',
        ARRAY ['amazon flex', 'amazon driver', 'amazon delivery'],
        'Subpoena to Amazon.com Services LLC. Flex drivers are contractors; request 1099 records.'
    ),
    (
        'Shipt',
        'CT Corporation System',
        '17 20th Street North',
        'Birmingham',
        'AL',
        '35203',
        ARRAY ['shipt', 'shipt shopper'],
        'Subpoena to Shipt, Inc. (Target subsidiary). Request shopper payment records.'
    ),
    (
        'Postmates',
        'CT Corporation System',
        '1515 3rd Street',
        'San Francisco',
        'CA',
        '94158',
        ARRAY ['postmates', 'post mates'],
        'Postmates merged with Uber. Subpoena to Uber Technologies, Inc. Reference Postmates fleet.'
    ) ON CONFLICT (platform_name) DO
UPDATE
SET registered_agent_name = EXCLUDED.registered_agent_name,
    registered_agent_address = EXCLUDED.registered_agent_address,
    registered_agent_city = EXCLUDED.registered_agent_city,
    registered_agent_state = EXCLUDED.registered_agent_state,
    registered_agent_zip = EXCLUDED.registered_agent_zip,
    detection_keywords = EXCLUDED.detection_keywords,
    subpoena_notes = EXCLUDED.subpoena_notes,
    updated_at = NOW();
-- ============================================================================
-- GIG DETECTIONS LOG TABLE
-- ============================================================================
-- Tracks when gig platform activity is detected for a judgment/plaintiff.
CREATE TABLE IF NOT EXISTS intelligence.gig_detections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    judgment_id BIGINT,
    plaintiff_id UUID,
    platform_id BIGINT REFERENCES intelligence.gig_platforms(id),
    -- Detection metadata
    detection_source TEXT,
    -- 'employer_name', 'enrichment', 'manual'
    matched_keyword TEXT,
    -- The keyword that triggered the match
    confidence_score NUMERIC(3, 2) DEFAULT 1.0,
    -- 0.00 - 1.00
    -- Subpoena status
    subpoena_generated BOOLEAN DEFAULT FALSE,
    subpoena_sent_at TIMESTAMPTZ,
    subpoena_document_url TEXT,
    -- Metadata
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_gig_detections_judgment ON intelligence.gig_detections(judgment_id);
CREATE INDEX IF NOT EXISTS idx_gig_detections_plaintiff ON intelligence.gig_detections(plaintiff_id);
CREATE INDEX IF NOT EXISTS idx_gig_detections_platform ON intelligence.gig_detections(platform_id);
-- ============================================================================
-- PERMISSIONS
-- ============================================================================
GRANT SELECT,
    INSERT,
    UPDATE ON intelligence.gig_platforms TO authenticated,
    service_role;
GRANT SELECT,
    INSERT,
    UPDATE ON intelligence.gig_detections TO authenticated,
    service_role;
GRANT USAGE,
    SELECT ON ALL SEQUENCES IN SCHEMA intelligence TO authenticated,
    service_role;
-- RLS policies (permissive for internal ops use)
ALTER TABLE intelligence.gig_platforms ENABLE ROW LEVEL SECURITY;
ALTER TABLE intelligence.gig_detections ENABLE ROW LEVEL SECURITY;
-- Service role full access
CREATE POLICY gig_platforms_service_all ON intelligence.gig_platforms FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY gig_detections_service_all ON intelligence.gig_detections FOR ALL TO service_role USING (true) WITH CHECK (true);
-- Authenticated users can read platforms
CREATE POLICY gig_platforms_auth_read ON intelligence.gig_platforms FOR
SELECT TO authenticated USING (true);
-- Authenticated users can read/write detections
CREATE POLICY gig_detections_auth_all ON intelligence.gig_detections FOR ALL TO authenticated USING (true) WITH CHECK (true);
-- ============================================================================
-- UTILITY VIEW - Active Platforms with Full Address
-- ============================================================================
CREATE OR REPLACE VIEW intelligence.v_gig_platforms_active AS
SELECT id,
    platform_name,
    registered_agent_name,
    registered_agent_address,
    registered_agent_city,
    registered_agent_state,
    registered_agent_zip,
    CONCAT_WS(
        ', ',
        NULLIF(registered_agent_address, ''),
        NULLIF(registered_agent_city, ''),
        CONCAT(
            registered_agent_state,
            ' ',
            registered_agent_zip
        )
    ) AS full_address,
    detection_keywords,
    subpoena_notes
FROM intelligence.gig_platforms
WHERE is_active = TRUE;
GRANT SELECT ON intelligence.v_gig_platforms_active TO authenticated,
    anon,
    service_role;
-- ============================================================================
-- DONE
-- ============================================================================