-- Migration: Create FOIL request tracking tables for automated follow-ups
-- Creates foil_requests table for tracking outgoing FOIL requests
-- Creates foil_followup_log for tracking follow-up attempts
-- 
-- NOTE: This migration is fully idempotent - safe to run multiple times.
-- ============================================================================
-- FOIL Requests table
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.foil_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_number TEXT NOT NULL,
    judgment_id BIGINT REFERENCES public.judgments(id) ON DELETE
    SET NULL,
        agency_name TEXT NOT NULL,
        agency_email TEXT,
        request_type TEXT NOT NULL DEFAULT 'standard',
        status TEXT NOT NULL DEFAULT 'pending',
        sent_at TIMESTAMPTZ,
        response_received_at TIMESTAMPTZ,
        notes TEXT,
        metadata JSONB DEFAULT '{}',
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT foil_requests_status_check CHECK (
            status IN (
                'draft',
                'pending',
                'followup_sent',
                'responded',
                'denied',
                'completed',
                'cancelled'
            )
        )
);
-- Indexes for common queries
CREATE INDEX IF NOT EXISTS idx_foil_requests_status ON public.foil_requests(status);
CREATE INDEX IF NOT EXISTS idx_foil_requests_created_at ON public.foil_requests(created_at);
CREATE INDEX IF NOT EXISTS idx_foil_requests_case_number ON public.foil_requests(case_number);
-- ============================================================================
-- FOIL Follow-up Log table
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.foil_followup_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    foil_request_id BIGINT NOT NULL REFERENCES public.foil_requests(id) ON DELETE CASCADE,
    attempted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    message_preview TEXT,
    success BOOLEAN DEFAULT true,
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_foil_followup_log_request_id ON public.foil_followup_log(foil_request_id);
-- ============================================================================
-- Updated at trigger for foil_requests
-- ============================================================================
CREATE OR REPLACE FUNCTION public.foil_requests_touch_updated_at() RETURNS TRIGGER AS $$ BEGIN NEW.updated_at = NOW();
RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS trg_foil_requests_updated_at ON public.foil_requests;
CREATE TRIGGER trg_foil_requests_updated_at BEFORE
UPDATE ON public.foil_requests FOR EACH ROW EXECUTE FUNCTION public.foil_requests_touch_updated_at();
-- ============================================================================
-- RLS policies (idempotent)
-- ============================================================================
ALTER TABLE public.foil_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.foil_followup_log ENABLE ROW LEVEL SECURITY;
-- Policy: foil_requests_service_all (service role full access)
DO $$ BEGIN IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
        AND tablename = 'foil_requests'
        AND policyname = 'foil_requests_service_all'
) THEN CREATE POLICY foil_requests_service_all ON public.foil_requests FOR ALL USING (auth.role() = 'service_role');
END IF;
END $$;
-- Policy: foil_followup_log_service_all (service role full access)
DO $$ BEGIN IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
        AND tablename = 'foil_followup_log'
        AND policyname = 'foil_followup_log_service_all'
) THEN CREATE POLICY foil_followup_log_service_all ON public.foil_followup_log FOR ALL USING (auth.role() = 'service_role');
END IF;
END $$;
-- Policy: foil_requests_select (authenticated/anon read)
DO $$ BEGIN IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
        AND tablename = 'foil_requests'
        AND policyname = 'foil_requests_select'
) THEN CREATE POLICY foil_requests_select ON public.foil_requests FOR
SELECT USING (auth.role() IN ('authenticated', 'anon'));
END IF;
END $$;
-- Policy: foil_followup_log_select (authenticated/anon read)
DO $$ BEGIN IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
        AND tablename = 'foil_followup_log'
        AND policyname = 'foil_followup_log_select'
) THEN CREATE POLICY foil_followup_log_select ON public.foil_followup_log FOR
SELECT USING (auth.role() IN ('authenticated', 'anon'));
END IF;
END $$;
-- ============================================================================
-- Grants (idempotent by nature)
-- ============================================================================
GRANT SELECT ON public.foil_requests TO anon,
    authenticated;
GRANT ALL ON public.foil_requests TO service_role;
GRANT SELECT ON public.foil_followup_log TO anon,
    authenticated;
GRANT ALL ON public.foil_followup_log TO service_role;
-- ============================================================================
-- Comments
-- ============================================================================
COMMENT ON TABLE public.foil_requests IS 'Tracks outgoing FOIL (Freedom of Information Law) requests';
COMMENT ON TABLE public.foil_followup_log IS 'Log of automated follow-up attempts for FOIL requests';
