-- ============================================================================
-- Migration: Enforcement Radar Filter Support
-- Created: 2025-12-10
-- Purpose: Add RPC function for enforcement radar with optional filters
-- ============================================================================
-- NOTE: This migration had a bug (UUID vs BIGINT type mismatch, debtor_intelligence join issue).
-- It has been converted to a no-op. The correct implementation is in
-- 20251223001000_fix_enforcement_radar_filter.sql which follows immediately.
-- ============================================================================
-- No-op: See 20251223001000_fix_enforcement_radar_filter.sql for the actual implementation
SELECT 1;